"""empty message

Revision ID: 863edf6207ce
Revises: 5f618cf28232
Create Date: 2020-05-10 08:04:12.139963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863edf6207ce'
down_revision = '5f618cf28232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writer', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writer', 'pass_secure')
    # ### end Alembic commands ###
