"""empty message

Revision ID: b2e097db8eba
Revises: e7297030e53c
Create Date: 2020-05-10 19:57:20.936540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e097db8eba'
down_revision = 'e7297030e53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'time')
    # ### end Alembic commands ###
