"""empty message

Revision ID: e0324c6371c0
Revises: 863edf6207ce
Create Date: 2020-05-10 08:38:00.837808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0324c6371c0'
down_revision = '863edf6207ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writer', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('writer', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writer', 'profile_pic_path')
    op.drop_column('writer', 'bio')
    # ### end Alembic commands ###
